package org.thp.thehive.services

import org.thp.scalligraph.query.PredicateOps
import org.thp.scalligraph.traversal.TraversalOps

trait TheHiveOps
    extends TraversalOps
    with PredicateOps
    with TaskOps
    with PatternOps
    with AuditOps
    with TaxonomyOps
    with ImpactStatusOps
    with ObservableTypeOps
    with ProfileOps
    with ShareOps
    with CaseTemplateOps
    with ConfigOps
    with LogOps
    with PageOps
    with ObservableOps
    with UserOps
    with AttachmentOps
    with DashboardOps
    with ProcedureOps
    with DataOps
    with CustomFieldOps
    with CaseOps
    with AlertOps
    with ReportTagOps
    with ResolutionStatusOps
    with TagOps
    with RoleOps
    with OrganisationOps
